apiVersion: v1
kind: Service
metadata:
  name: service-orders
spec:
  selector:
    app: service-orders
  type: NodePort
  ports:
    - name: http
      port: 8082
      nodePort: 32000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-orders
spec:
  selector:
    matchLabels:
      app: service-orders
  replicas: 1
  template:
    metadata:
      labels:
        app: service-orders
    spec:
      containers:
        - name: server
          image: bobovik/orders
          ports:
            - name: http
              containerPort: 8082

---