apiVersion: v1
kind: Service
metadata:
  name: service-identities
spec:
  selector:
    app: service-identities
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-identities
spec:
  selector:
    matchLabels:
      app: service-identities
  replicas: 1
  template:
    metadata:
      labels:
        app: service-identities
    spec:
      containers:
        - name: server
          image: bobovik/identities
          ports:
            - name: http
              containerPort: 8081

---